### ISSUE TITLE
Question about the textured mesh?

### ISSUE THREAD

**Issue by JanaldoChen** [jby1993/SelfReconCode#3]
How to get the textured mesh?

**Comment by JanaldoChen** [comment]
When I use VideoAvatar to extract the texture from the images, I met this problem:
Traceback (most recent call last):
  File "get_texture.py", line 220, in <module>
    main(args.images_dir, args.masks_dir, args.meshes_dir, args.mesh, args.camera, args.out, args.resolution, args.num, args.first_frame, args.last_frame, args.display)
  File "get_texture.py", line 122, in main
    part_tex = iso.render(frame / 255., camera, visible_faces)
  File "/media/Janaldo_data/Janaldo_workspace/videoavatars/tex/iso.py", line 34, in render
    mask = np.atleast_3d(self.rn_vis.r)
  File "/home/janaldo/miniconda3/envs/videoavatar/lib/python2.7/site-packages/chumpy/ch.py", line 596, in r
    self._cache['r'] = np.asarray(np.atleast_1d(self.compute_r()), dtype=np.float64, order='C')
  File "/media/Janaldo_data/Janaldo_workspace/videoavatars/render/renderer.py", line 54, in compute_r
    return self.color_image
  File "/home/janaldo/miniconda3/envs/videoavatar/lib/python2.7/site-packages/chumpy/ch.py", line 1213, in with_caching
    sdf['value'] = func(self, *args, **kwargs)
  File "/media/Janaldo_data/Janaldo_workspace/videoavatars/render/renderer.py", line 97, in color_image
    return super(OrthoColoredRenderer, self).color_image
  File "/home/janaldo/miniconda3/envs/videoavatar/lib/python2.7/site-packages/chumpy/ch.py", line 1213, in with_caching
    sdf['value'] = func(self, *args, **kwargs)
  File "/home/janaldo/miniconda3/envs/videoavatar/lib/python2.7/site-packages/opendr/renderer.py", line 386, in color_image
    no_overdraw = self.draw_color_image(gl)
  File "/home/janaldo/miniconda3/envs/videoavatar/lib/python2.7/site-packages/opendr/renderer.py", line 371, in draw_color_image
    draw_colored_verts(gl, self.v.r, self.f, self.vc.r)
  File "/home/janaldo/miniconda3/envs/videoavatar/lib/python2.7/site-packages/opendr/renderer.py", line 852, in draw_colored_verts
    gl.DrawElements(GL_TRIANGLES, np.asarray(f, np.uint32).ravel())
  File "contexts/ctx_base.pyx", line 24, in contexts.ctx_mesa.mc.with_make_current
  File "contexts/ctx_base.pyx", line 188, in contexts.ctx_mesa.OsContextBase.DrawElements
IndexError: Out of bounds on buffer access (axis 0)
Did you have met this problem? How to fix this?

**Comment by Onlybyuse** [comment]
Thank you for sharing your excellent work. I also have met the same problem. How to solve this? Thanks！ @jby1993 @Juyong

**Comment by jby1993** [comment]
Do you want to extract the texture for the results of  SelfRecon? You need to uv-parameterize the template mesh first and extract the forward geometry and convert the results to VideoAvatar's format to extract the texture.

**Comment by JanaldoChen** [comment]
Thanks for your reply! I have got the obj mesh with uv-parameterization using the blender, but I don't how to convert the results to VideoAvatar's format, Can you provide the code?

**Comment by JanaldoChen** [comment]
When I run the SelfReconCode on my video, I got the blurred color image, while the geometry seems OK.  So I want to how to get the textured mesh as you have shown.
![0_g](https://user-images.githubusercontent.com/44859515/172798121-7d3028fe-6e14-41c7-92f4-b2f9edd97e7b.png)
![0_g](https://user-images.githubusercontent.com/44859515/172798138-f7cb4d23-abe7-4c30-8e24-f9ac77a41b85.png)

**Comment by jby1993** [comment]
> Thanks for your reply! I have got the obj mesh with uv-parameterization using the blender, but I don't how to convert the results to VideoAvatar's format, Can you provide the code?

This part of the script is still being worked out.

**Comment by JanaldoChen** [comment]
Thanks once again, I'm really looking forward to it!

**Comment by JanaldoChen** [comment]
Thanks a lot! I will try it.

**Comment by Xianjin111** [comment]
> Thanks a lot! I will try it.

I would like to ask whether you could reconstruct the effect of published data? Thank you very much.
