### ISSUE TITLE
which project did you use to create masks?

### ISSUE THREAD

**Issue by Riraifu** [jby1993/SelfReconCode#32]
I use PaddleSeg to create masks,but it seems that the results are not good enough.When I run step2 in VideoAvatar, there is something wrong with it.

  n /= np.linalg.norm(n, axis=1).reshape(-1, 1)
 78%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                        | 94/120 [00:16<00:04,  5.81it/s]
Traceback (most recent call last):
  File "step2_consensus.py", line 206, in <module>
    args.first_frame, args.last_frame, args.nohands, args.naked, args.display)
  File "step2_consensus.py", line 135, in main
    fit_consensus(frames, base_smpl, camera, frustum, model_data, nohands, icp_count, naked, display)
  File "step2_consensus.py", line 81, in fit_consensus
    E['silh_{}'.format(current)] = ray_objective(f, sigma, base_smpl, camera, vis_rn_b, vis_rn_m)
  File "/home/zhuly59/CODE/videoavatars2/lib/rays.py", line 96, in ray_objective
    f.v_ids, f.rays_u = unpose_and_select_rays(f.rays, f.Vi, base_smpl, vis_rn_b, vis_rn_m)
  File "/home/zhuly59/CODE/videoavatars2/lib/rays.py", line 34, in unpose_and_select_rays
    ray_matches = np.argmin(dist, axis=0)
  File "/home/zhuly59/anaconda3/envs/VideoAvatar/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 1172, in argmin
    return _wrapfunc(a, 'argmin', axis=axis, out=out)
  File "/home/zhuly59/anaconda3/envs/VideoAvatar/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 56, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: attempt to get argmin of an empty sequence

**Comment by jby1993** [comment]
We use multi-methods. Some are processed like VideoAvatar or other models. For some difficult data, we also utilize PS to process.

**Comment by Riraifu** [comment]
> We use multi-methods. Some are processed like VideoAvatar or other models. For some difficult data, we also utilize PS to process.

Thanks for your reply. How did you create masks only in your own dataset female-3?  I use PaddleSeg,but is doesn't work. I also use a code that preprocess with the green background,but it doesn't work neither.

**Comment by vastskymiaow** [comment]
Hi, I'm a rookie in CV. I'm also confused in preprocessing my own data in #31 .
So is there a tutorial to create files? Tutorial  in https://github.com/thmoa/videoavatars is not friendly.

**Comment by jby1993** [comment]
We use VideoAvatar to estimate smpl and camera initialization.  The mask is produced with the method described above. For data in PeopleSnapshot, we use the supplied data as initialization.
