### ISSUE TITLE
关于在执行代码时缺少包“GridSamplerMine”的问题。

### ISSUE THREAD

**Issue by ghost** [jby1993/SelfReconCode#39]
您好，我在执行 CUDA_VISIBLE_DEVICES=1 python train.py --gpu-ids 0 --conf config.conf --data female-3-casual --save-folder result时，返回了如下的错误。

Traceback (most recent call last):
  File "train.py", line 3, in <module>
    from dataset.dataset import getDatasetAndLoader
  File "/home/gaoxin/sfc/SelfReconCode-main/dataset/dataset.py", line 7, in <module>
    import utils
  File "/home/gaoxin/sfc/SelfReconCode-main/utils/__init__.py", line 3, in <module>
    from .utils import *
  File "/home/gaoxin/sfc/SelfReconCode-main/utils/utils.py", line 230, in <module>
    from MCAcc import Seg3dLossless
  File "/home/gaoxin/sfc/SelfReconCode-main/MCAcc/__init__.py", line 3, in <module>
    from .grid_sampler_mine import GridSamplerMine3dFunction
  File "/home/gaoxin/sfc/SelfReconCode-main/MCAcc/grid_sampler_mine.py", line 6, in <module>
    import GridSamplerMine
ModuleNotFoundError: No module named 'GridSamplerMine'。

我多次重装环境后无果，请问可以介绍下这个包的来源吗，又或者是我在配环境时忽略了一些错误？希望能得到回复，感谢！

**Comment by jby1993** [comment]
你需要安装repo里的[MCAcc](https://github.com/jby1993/SelfReconCode/tree/main/MCAcc)，bash install.sh应该会安装这几个自定义库的，你可能没有装成功

**Comment by ghost** [comment]
好的，感谢回复！


.
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jby1993/SelfReconCode"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月8日(星期一) 下午4:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jby1993/SelfReconCode] 关于在执行代码时缺少包“GridSamplerMine”的问题。 (Issue #39)





 
你需要安装repo里的MCAcc，bash install.sh应该会安装这几个自定义库的，你可能没有装成功
